### ISSUE TITLE
Huge edit icons

### ISSUE THREAD

**Issue by hakimio** [phalcon/docs#1458]
What's with the huge edit icons next to section headers? Also, the icon messes-up google indexing. When you search for "phalcon apcu", one of the result titles says "Class Phalcon\Annotations\Adapter\Apcu Edit".

**Comment by ninjapanzer** [comment]
As far as the size, it looks like the CSS cache was not regenerated on last deploy @niden ?

The google indexing is due to the fact that the edit icon is within the `<h1>` tag and should be next to it. Search engines really care about the contents of `<h1>` apparently even the alt text of an image.
@garyanewsome can you help me reorganize the pencil icon so it is outside the `<h1>` tags

**Comment by emiliodeg** [comment]
For some reason headings don't looks like @garyanewsome show in [the pull #53](https://github.com/phalcon/docs-app/pull/53)

**Comment by ninjapanzer** [comment]
Resolved with cache bust and https://github.com/phalcon/docs-app/pull/54
