### ISSUE TITLE
Inject Service into Volt Template is not correct

### ISSUE THREAD

**Issue by AugustHell** [phalcon/docs#1515]
The documentation:
https://docs.phalconphp.com/en/3.2/volt
Inject Services into a Template
> "If a service container (DI) is available for Volt, you can use the services by only accessing the name of the service in the template"

Example:
Having a service with the name "servicename" that outputs a string
Using `{{ servicename }}` leads to a variable not found exception
or `{{ servicename() }}` fires a volt makro exception
Only way I found, that works was: `{{ this.servicename }}`

The given code example on the pages:
`{{ flash.output() }}` and `{{ security.getToken() }}` 
referencing methods of the service, works and is correct.

`

**Comment by emiliodeg** [comment]
Hi @AugustHell I don't have this problem in my projects probably you have an mistake in your services configuration

**Comment by niden** [comment]
I have never seen this in any of my projects.

If I define a service `servicename` in my DI container, I can use it in Volt with no problem.

If you do in Volt `{{ servicename }}` it will complain because it thinks it is a variable. Your service should be an object that does something. So if you have something like this:

```
servicename->hello()
servicename->goodbye()
```
then in Volt you will use
```
{{ servicename.hello() }}
{{ servicename.goodbye() }}
```
Assuming that an object is a variable to be printed out is not correct and Volt does that - it thinks that this is not a service but a variable.

Closing as this is not a problem with the documentation.

**Comment by emiliodeg** [comment]
`{{ servicename..goodbye() }}` two dots?

**Comment by niden** [comment]
@emiliodeg one. corrected it. Thanks
