### ISSUE TITLE
Application as Proofreader for Tagalog/Filipino Translation

### ISSUE THREAD

**Issue by ergiegonzaga** [phalcon/docs#1545]
Hi sir, 
Good day, Please allow me to become a proofreader for your tagalog/Filipino localization in crowdin sir.

Ill be waiting for your response sir,
More power and godbless.

**Comment by ergiegonzaga** [comment]
Hi sir,
Good day! 
I want to ask if did you remove the Tagalog/Fipino Translation for your Phalcon Documentation ?

**Comment by niden** [comment]
Thank you for your interest in helping with the translations for our project. We do not grant proofreader access randomly. Our proofreaders have been contributing to our project for quite a while now and have earned the new role, because we want to ensure that our documentation is of the highest quality. If you wish to become proofreader, start contributing to the project. Once we review your contributions, we will be able to have a better idea on whether you can become a proofreader or not. We have had serious problems with translators who were not technical and were translating methods and classes of the framework, making our documentation worse and not better.

Thank you for your understanding and looking forward to your contributions

**Comment by niden** [comment]
Yes for now Filipino and Tagalog have been removed so that we can clean up the documentation. Once we are able to do that, we can readd the languages

**Comment by ergiegonzaga** [comment]
Okay sir, I was so shocked upon seeing that the Filipino and Tagalog Translations were removed. All my 5 utopian.io contributions were disapproved ddue to that sir because moderators cannot see anymore the Filipino and Tagalog Translations aw well as my status as a proofreader of your project in the said language. If Filipino ang Tagalog Tranlations wil be back, may I become a proofreader again sir? please? And if I could do any help on the cleaning of documentation sir. Please inform me.

More Power and Godbless.
