### ISSUE TITLE
Old docs layout is better

### ISSUE THREAD

**Issue by martinadi** [phalcon/docs#1608]
hi,
i thing old docs layout is better than new docs layout. in old docs all text is indexable by google so easy to search. if i search some doc on google i always found information from olddocs. in old docs widh of content are fluid this is easy to read long coding.
Thanks you

**Comment by niden** [comment]
Thank you for reporting this.

We have recently made alterations to our olddocs and main docs site to handle all the redirects so that Google or other search engines update their indexes. 

The new docs site also has the custom search enabled so that could be something you can use.

Closing this issue.
