### ISSUE TITLE
Will the language package be displayed only after the translation is complete?

### ISSUE THREAD

**Issue by dongasai** [phalcon/docs#1922]
Will the language packs that have not been translated completed be displayed?
I am a participant in the translation of Chinese language packs.

**Comment by niden** [comment]
@dongasai Thank you for your contributions. The way the process works is:

- Source language is `en`. We only change that language here in github. Everything else is handled by Crowdin.
- Contributors go to Crowdin and translate as much or as little as they want
- For every language the text needs to be approved by a proofreader
- Once it is approved, it gets pulled (manually) to our site.

I am not sure if we have a proofreader for Chinese so send me a message in Crowdin and I can help you there so that once you approve the strings the content will be up.

**Comment by niden** [comment]
@dongasai After you approve certain translations, let me know so that I can deploy and you can check it on the live site. After that we can close this issue.

**Comment by dongasai** [comment]
ok
