### ISSUE TITLE
v4: Rewrite filter.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2121]

**Comment by niden** [comment]
cc @CameronHall @ruudboon  Comments please:

https://docs.phalconphp.com/4.0/en/filter

**Comment by ruudboon** [comment]
In general a good document.
Small things I've noticed. 

>It uses preg_replace which can also accept arrays of strings as the parameters.
Maybe we can make a general note of this instead of adding this to multiple filters

**Sanitizing data**
> Sanitizing is the process which removes specific characters from a value
Isn't this the other way around? Only allowing specific characters? (Deny default)
```
// Is this removing ( ) \ or only allowing a-z + @ .
$locator->sanitize('some(one)@exa\mple.com', 'email');
```

Upgrading to V3 line can be removed if we keep the upgrade button in the top.

**Comment by niden** [comment]
Ok these have been addressed and pushed upstream
