### ISSUE TITLE
v4: Rewrite logging.md

### ISSUE THREAD

**Issue by niden** [phalcon/docs#2130]

**Comment by niden** [comment]
@ruudboon @CameronHall When you guys get a chance

https://docs.phalconphp.com/4.0/en/logger
https://docs.phalconphp.com/4.0/el-gr/logger

**Comment by ruudboon** [comment]
Thnx @niden well done!

Some feedback

**logger-overview** 
In the end you discuss the differences with v3. Shouldn't this be part of the upgrade instructions? 

**Logger Adapter**
Love the colleagues joke on the noop adapter!
Factory, maybe add a link to the project on GitHub so people can see the status?

** Instantiating a logger **
Menu link has wrong title (it says creating a logger component)

[Interpolation](url)

> This means that you can inject data to a message based on the needs of your application.

Can we make this a bit easier to understand? Something like: Based on your application needs you might want to customise the message. You can do this by adding parameters to the message.

Or 

This means that you can customise the message based on parameters.


Will these pages get combined in one page? Otherwise we should add some menu to navigate and have a look at the page header titles. Personally I would not mind if you can read a bit more before you  need to click again.

**Comment by niden** [comment]
Which reminds me - update the upgrade document. 

- I combined the overview with the main links page (one page less now). I would leave the upgrade message there and expand more in the upgrade page.
- Added a link to the issue for the factory
- Corrected the instantiating
- Cleared up a bit the interpolation

**Comment by niden** [comment]
The pages will stay as they are, split in smaller parts because we will introduce comments. There is already the right side menu as well as the previous/next topic navigation at the bottom of each page.
