### ISSUE TITLE
Docs down (404)

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/docs#2339]
@niden all links to 3.4 docs are down?
https://docs.phalconphp.com/3.4/en/api/Phalcon_Http_Request

**Comment by niden** [comment]
@scrnjakovic Thanks I will sort it out tonight. Need to fix some redirects I guess

**Comment by Arhell** [comment]
@scrnjakovic, fix

**Comment by scrnjakovic** [comment]
Fixed, closing. Thanks @niden.

**Comment by scrnjakovic** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3901248/61129619-10d5e580-a4b5-11e9-9c89-5875b78b43d4.png">

**Comment by niden** [comment]
It works now. https://docs.phalconphp.com/3.4/en/api/Phalcon_Mvc_View

The landing page has an issue which I am resolving now

**Comment by scrnjakovic** [comment]
@niden Thanks. Can we close now?

**Comment by niden** [comment]
Yeah we can close it. There are a few dead links that I am working on but it takes a bit of time to identify them all.

**Comment by scrnjakovic** [comment]
https://docs.phalconphp.com/3.4/en/api/phalcon_http redirects to cookie api page.

**Comment by niden** [comment]
Actually that one is correct. It should redirect to `Phalcon_Http` which is a collection of API documents for the http namespace. Cookie is just the first of the classes. If you look at the menu on the left it has all the Http classes there

And before you ask, I combined API docs based on their namespaces because we were serving close to 3000 files in total (with the translations) and that was very close to the max allowed time to build the documents.

**Comment by scrnjakovic** [comment]
Oh, okay. I was confused because I was clicking on the link `Phalcon\Http\Request` on https://docs.phalconphp.com/3.4/en/request and got cookies instead. Didn't even see the menu on the left 😞

**Comment by niden** [comment]
Closing this - it has been resolved. Please reopen if any issues are identified
